os: linux
dist: bionic
language: cpp

addons:
  homebrew:
    packages:
    - gcc@9

jobs:
  include:
    - stage: test
      name: check-apple-gcc
      os: osx
      osx_image: xcode12.5
      script: true