os: linux
dist: bionic
language: cpp

addons:
  homebrew:
    update: true
    packages:
    - gcc@9

jobs:
  include:
    - stage: test
      name: check-apple-gcc
      os: osx
      osx_image: xcode12
      script: true
      
    # Test that the project builds and tests successfully on OSX with Apple Clang
    - stage: test
      name: check-apple-clang
      os: osx
      osx_image: xcode12
      script: true