os: linux
dist: bionic
language: cpp

addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - g++-7
    - g++-9
    - clang-10
    - libomp-10-dev
    - libtbb-dev
    - libc++1-10
    - libc++abi1-10
    - libc++-10-dev
    - libc++abi-10-dev
  homebrew:
    update: false
    packages:
    - gcc@9

script: true